name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest

    env:
     CONFIGURATION: Release
     PACKAGES_DIR: ${{ github.workspace }}\nupkgs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Clean old NuGet packages
      shell: pwsh
      run: |
          New-Item -ItemType Directory -Force "$env:PACKAGES_DIR" | Out-Null
          Remove-Item "$env:PACKAGES_DIR\*.nupkg" -ErrorAction SilentlyContinue

    - name: Decode and save .snk file
      shell: pwsh
      run: |
        $base64String = "${{ secrets.SNK_KEY_BASE64 }}"
        $bytes = [System.Convert]::FromBase64String($base64String)
        [System.IO.File]::WriteAllBytes("Assets/UWN-GH.snk", $bytes)

    - name: Build and create NuGet package
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore -p:GeneratePackageOnBuild=true -p:PackageOutputPath="${{ env.PACKAGES_DIR }}"

    - name: Remove the .snk file
      run: Remove-Item Assets/UWN-GH.snk -ErrorAction SilentlyContinue

    - name: Publish to NuGet
      run: dotnet nuget push "${{ env.PACKAGES_DIR }}\*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
